source 'https://github.com/CocoaPods/Specs.git'

target 'TTPLTestReport', :exclusive => true do
  pod "TTPLTestReport", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TTPLTestReport", :path => "../"

  
end
